{"name": "test_myntra_homepage", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nPlease use the Async API instead.", "trace": "def test_myntra_homepage():\n>       with sync_playwright() as p:\n\ntest_page_load.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright.sync_api._context_manager.PlaywrightContextManager object at 0x1030cb140>\n\n        def __enter__(self) -> SyncPlaywright:\n            try:\n                self._loop = asyncio.get_running_loop()\n            except RuntimeError:\n                self._loop = asyncio.new_event_loop()\n                self._own_loop = True\n            if self._loop.is_running():\n>               raise Error(\n                    \"\"\"It looks like you are using Playwright Sync API inside the asyncio loop.\n    Please use the Async API instead.\"\"\"\n                )\nE               playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.\nE               Please use the Async API instead.\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/playwright/sync_api/_context_manager.py:47: Error"}, "start": 1759769083473, "stop": 1759769083473, "uuid": "fb7a76f2-91d7-4779-a2dc-2fb4b9f347cb", "historyId": "7227a9a70937b8f4e5f9695030db3c83", "testCaseId": "7227a9a70937b8f4e5f9695030db3c83", "fullName": "test_page_load#test_myntra_homepage", "labels": [{"name": "suite", "value": "test_page_load"}, {"name": "host", "value": "WQM1Q0Q4X9"}, {"name": "thread", "value": "82990-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_page_load"}], "titlePath": ["test_page_load.py"]}